name: ci

on:
  push:
    branches: ["develop"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  UnitTest:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # base64 < .env
      - name: Create .env file
        run: |
          echo "${{ secrets.BUILDENV }}" | base64 -d > .env
          ls -la .env
        
      # base64 < .env.test
      - name: Create .env.test file
        run: |
          echo "${{ secrets.TESTENV }}" | base64 -d > .env.test
          ls -la .env.test

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Build
        run: pnpm run build
        timeout-minutes: 3

      - name: Run UI:Test
        run: xvfb-run npx playwright test
        timeout-minutes: 20

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screen recording
          path: tests/archive/screenrecord/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: network recording
          path: tests/archive/network/
          retention-days: 30
     
      - uses: actions/upload-artifact@v3
        if: success()
        with:
         name: dist
         path: dist/
         retention-days: 30

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
         name: dist(failure)
         path: dist/
         retention-days: 1